/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControlTablaEstudiante;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import modelo.RegistroEstudiante;

/**
 *
 * @author Raul
 */
public class GUITablaEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form GUITablaEstudiante
     */

    public GUITablaEstudiante(RegistroEstudiante registroEst) {
        initComponents();
        ControlTablaEstudiante control=new ControlTablaEstudiante(registroEst,this);
        this.escuchar(control);
        this.cargarFiltro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtData = new javax.swing.JTable();
        btnRegistro = new javax.swing.JButton();
        cboxCategoria = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        lbCategoria = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(65, 173, 231));

        jtData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Carnet", "Nombre", "Edad"
            }
        ));
        jScrollPane1.setViewportView(jtData);

        btnRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar.png"))); // NOI18N
        btnRegistro.setActionCommand("Registro");

        cboxCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 219, 6));
        jLabel1.setText("Filtro:");

        lbCategoria.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbCategoria.setForeground(new java.awt.Color(255, 219, 6));
        lbCategoria.setText("Dato:");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        btnBuscar.setActionCommand("Buscar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(2, 2, 2)
                        .addComponent(cboxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cboxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCategoria))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JComboBox cboxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtData;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

    public static final String BTN_REGISTRO = "Registro";
    public static final String BTN_BUSCAR = "buscar";
    
    public void escuchar(ControlTablaEstudiante control) {
        this.btnRegistro.addActionListener(control);
        this.btnBuscar.addActionListener(control);
        this.cboxCategoria.addItemListener(control);
        this.jtData.addMouseListener(control);
    }
    
    public String getTxtBuscar() {
        return this.txtBuscar.getText();
    }
    
    public String getCboxCategoria() {
        return this.cboxCategoria.getSelectedItem().toString();
    }
    
    public void setLbCategoria(String etiqueta){
        this.lbCategoria.setText(etiqueta);
    }
    
    public void enableCampoBuscar(boolean estado){
        this.txtBuscar.setEnabled(estado);
    }
    
    public void cargarFiltro() {
        String[] filtro = {"Seleccionar","All", "Carnet", "Nombre","Edad"};
        this.cboxCategoria.setModel(new DefaultComboBoxModel(filtro));
    }
    
    public void setValores(String[][] datosFilas, String etiquetas[]) {
        if (datosFilas != null) {
            jtData.setModel(new DefaultTableModel(datosFilas, etiquetas));
            jScrollPane1.setViewportView(jtData);
        }

    }
    
    public String[] getdatosFila() {
        String datos[] = new String[jtData.getColumnCount()];
        int filaSeleccionada = jtData.getSelectedRow();
        for (int columna = 0; columna < datos.length; columna++) {
            datos[columna] = jtData.getValueAt(filaSeleccionada, columna).toString().trim();
        }
        return datos;
    }
    
    public void limpiar(){
        txtBuscar.setText("");
    }
}
